@startuml
title QtApps依赖关系网

folder "Python库" {
    [wechat-login-sdk-py] #SkyBlue
}

folder "Django库" {
    [django-wechat-login] #SkyBlue
    [django-wechatpay] #SkyBlue
    [django-wecom] #SkyBlue
    [django-qcloud] #SkyBlue
    [django-qtauth] #SkyBlue
}

[wechat-login-sdk-py] --> [django-wechat-login]

folder "Flutter库" {
    [flutter-cloudbase] #SkyBlue
    [flutter-admin-widgets] #SkyBlue
}

folder "领域层" {
    [qtuser-server-django] #Orange
    () qtuser_auth_apis #SkyBlue
    () qtstaff_auth_apis #SkyBlue
    [qtpay-server-django] #SkyBlue
    () qtpay_apis #SkyBlue
}

[django-qcloud] --> [qtuser-server-django]
[django-wechat-login] --> [qtuser-server-django]
[django-wecom] --> [qtuser-server-django]
[qtuser-server-django] -- qtuser_auth_apis
[qtuser-server-django] -- qtstaff_auth_apis

[django-qtauth] --> [qtpay-server-django]
[django-wechatpay] --> [qtpay-server-django]
qtuser_auth_apis .up.> [qtpay-server-django]
[qtpay-server-django] -- qtpay_apis

folder "量潮课堂" {
    [qtclass-server-django] #Orange
    () qtclass_apis #SkyBlue
    () qtclass_admin_apis #SkyBlue
    [qtclass-client-flutter] #Orange
    [qtclass-admin-client-flutter] #SkyBlue
}

[django-qtauth] --> [qtclass-server-django]
qtuser_auth_apis ..> [qtclass-server-django]
qtpay_apis ..> [qtclass-server-django]
[qtclass-server-django] -- qtclass_apis
[qtclass-server-django] -- qtclass_admin_apis

[flutter-cloudbase] -up-> [qtclass-client-flutter]
qtclass_apis ..> [qtclass-client-flutter]
qtuser_auth_apis ..> [qtclass-client-flutter]
qtpay_apis ..> [qtclass-client-flutter]

[flutter-cloudbase] -up-> [qtclass-admin-client-flutter]
[flutter-admin-widgets] -up-> [qtclass-admin-client-flutter]
qtclass_admin_apis ..> [qtclass-admin-client-flutter]
qtstaff_auth_apis ..> [qtclass-admin-client-flutter]

folder "量潮数据服务" {
    [qtservices-server-django] #SkyBlue
    () qtservices_apis #SkyBlue
    () qtservices_admin_apis #SkyBlue
    [qtservices-client-wechatmp] #SkyBlue
    [qtservices-admin-client-flutter] #SkyBlue
}

qtservices_apis ..> [qtservices-client-wechatmp]
qtuser_auth_apis ..> [qtservices-client-wechatmp]
[django-qtauth] --> [qtservices-server-django]
qtuser_auth_apis ..> [qtservices-server-django]
[qtservices-server-django] -- qtservices_apis
[qtservices-server-django] -- qtservices_admin_apis

qtservices_apis ..> [qtservices-client-wechatmp]

[flutter-cloudbase] -up-> [qtservices-admin-client-flutter]
[flutter-admin-widgets] -up-> [qtservices-admin-client-flutter]
qtservices_admin_apis ..> [qtservices-admin-client-flutter]
qtstaff_auth_apis ..> [qtservices-admin-client-flutter]

folder "量潮企业后台" {
    [qtfinance-server-django] #Orange
    () qtfinance_apis #SkyBlue
    [qthr-server-django] #SkyBlue
    () qthr_apis #SkyBlue
    [qtfinance-client-flutter] #SkyBlue
    [qthr-client-flutter] #SkyBlue
}

[django-qtauth] --> [qtfinance-server-django]
qtstaff_auth_apis ..> [qtfinance-server-django]
[qtfinance-server-django] -- qtfinance_apis

[django-qtauth] --> [qtfinance-server-django]
qtstaff_auth_apis ..> [qthr-server-django]
[qthr-server-django] -- qthr_apis

[flutter-cloudbase] -up-> [qtfinance-client-flutter]
[flutter-admin-widgets] -up-> [qtfinance-client-flutter]
qtfinance_apis ..> [qtfinance-client-flutter]
qtstaff_auth_apis ..> [qtfinance-client-flutter]

[flutter-cloudbase] -up-> [qthr-client-flutter]
[flutter-admin-widgets] -up-> [qthr-client-flutter]
qthr_apis ..> [qthr-client-flutter]
qtstaff_auth_apis ..> [qthr-client-flutter]

@enduml